- name: Bring up Postgres container
  command: >
           /usr/local/bin/docker-compose -f 
           "{{SLM_ROOT}}/launch-postgres-compose.yml" up -d
           --no-recreate

- name: Ensure necessary ports are opened up
  wait_for: port="5432" delay=30 timeout=300

- name: Bring up Django webapp container
  command: >
           /usr/local/bin/docker-compose -f
           "{{SLM_ROOT}}/launch-webapp-compose.yml" up -d

- name: Bring up nginx container
  command: >
           /usr/local/bin/docker-compose -f
           "{{SLM_ROOT}}/launch-nginx-compose.yml" up -d

