"""
Django settings for slmwebsite project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.normpath(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bsd(pqk&#r0h!wt1*4&l(9(-0_dxv_wcl5ts32&v0+k9_=yqdg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SITE_ID = 1
ALLOWED_HOSTS = ['127.0.0.1',
                 'localhost',
                 'slmdevpodnginx.slmlab.com',
                 'slmweb.slmlab.com',
                ]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/api/'
LOGIN_EXEMPT_URLS = (
 r'^$',
 r'^about\.html$',
 r'^legal/', # allow any URL under /legal/*
 r'^accounts/login', # allow any URL under /legal/*
 r'^accounts/register', # allow any URL under /legal/*
 r'^accounts/logout', # allow any URL under /legal/*
# LOGOUT_URL.lstrip('/'),
) 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'permission',
    'django.contrib.sites',
    # For user registering/sign-up, log in etc.
    'registration',
    'social_django',
    'rest_framework',
    'rest_framework.authtoken',
    'helloslmapp',
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'permission.backends.PermissionBackend',
    )

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s ' +
                      '<%(process)d.%(threadName)s> [%(name)s] %(message)s',
            'datefmt': '%Y-%m-%dT%H:%M:%S%z'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('SLMWEBSITE_LOG_LEVEL', 'INFO'),
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),

    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.DjangoFilterBackend',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.DjangoObjectPermissions',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'helloslmapp.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'slmwebsite.urls'
USE_I18N = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'helloslmapp', 'templates'),
                 os.path.join(PROJECT_DIR, 'templates')
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'permission.templatetags.permissionif',
            ],
            'context_processors': [
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'slmwebsite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': 'slm.db',
     },
     'postgres': {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': 'slmdb',
         'USER': 'slmuser',
         'PASSWORD': 'slmpass',
         'HOST': '127.0.0.1',
         'PORT': 5432,
     }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
    )

ADMINS = [('slmadmin', 'slmadmin@slmlab.com')]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

MEDIA_ROOT = os.path.join(PROJECT_DIR, 'media')
MEDIA_URL = '/media/'

# Location where all static files are gathered by django in one single place.
# This should be an initially empty destination directory for collecting your
# static files from their permanent locations into one directory for ease of
# deployment - it is not a place to store your static files permanently.

STATIC_ROOT = os.path.join(PROJECT_DIR, 'static_contents')

STATIC_URL = '/static/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # DefaultStorageFinder is disabled by default. If enabled, it will look for
    # static files in the default file storage as defined by the
    # DEFAULT_FILE_STORAGE setting.
    # 'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'helloslmapp', 'staticfiles'),
                    os.path.join(PROJECT_DIR, 'staticfiles')]

REGISTRATION_OPEN = True

# from login_required_middleware import LoginRequiredMiddleware
try:
    from local_settings import *
except ImportError:
    pass
